package user_interface;

/* Generated By:JavaCC: Do not edit this line. CommandParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CommandParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 6;
  /** RegularExpression Id. */
  int UPDATE = 7;
  /** RegularExpression Id. */
  int HELP = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int CHARACTER = 11;
  /** RegularExpression Id. */
  int WORD = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "<EXIT>",
    "\"update\"",
    "\"help\"",
    "<NUMBER>",
    "<DIGIT>",
    "<CHARACTER>",
    "<WORD>",
    "\"-l\"",
    "\"-a\"",
    "\"-d\"",
    "\"-f\"",
  };

}
